# Global settings (optional)
fail_fast: false
default_stages: [pre-commit, pre-push]

repos:
  # 1. General housekeeping (whitespace, line endings, YAML checks)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-yaml

  # 2. C/C++ formatting via clang-format
  - repo: https://github.com/glotzerlab/pre-commit-clang-format
    rev: v1.1.0
    hooks:
      - id: clang-format
        args: [--style=LLVM]        # or Google, Mozilla, etc. :contentReference[oaicite:2]{index=2}

  # 3. C/C++ static analysis (clang-tidy, cppcheck, include-what-you-use)
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-tidy           # C++ warnings & best practices :contentReference[oaicite:3]{index=3}
      - id: cppcheck             # catch null derefs, memory leaks :contentReference[oaicite:4]{index=4}
      - id: include-what-you-use # enforces correct #includes :contentReference[oaicite:5]{index=5}

  # 4. Shell script linting via ShellCheck
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: shellcheck          # detect common shell scripting errors :contentReference[oaicite:6]{index=6}

  # 5. Commit-message linting (Conventional Commits)
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v1.6.0
    hooks:
      - id: commitlint
        stages: [commit-msg]     # enforce commit-msg format :contentReference[oaicite:7]{index=7}
